name: CI
on:
  push:
  pull_request:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Setup NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Run `yarn install`
        uses: borales/actions-yarn@v5
        with:
          cmd: install
    
      - name: Run ESLint
        uses: borales/actions-yarn@v5
        with:
          cmd: lint
